//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AI_BTS_DENSOEntities1 : DbContext
    {
        public AI_BTS_DENSOEntities1()
            : base("name=AI_BTS_DENSOEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIVE_MST> ACTIVE_MST { get; set; }
        public virtual DbSet<BIN_MST> BIN_MST { get; set; }
        public virtual DbSet<BIN_TYPE_MST> BIN_TYPE_MST { get; set; }
        public virtual DbSet<CATEGORY_MST> CATEGORY_MST { get; set; }
        public virtual DbSet<DEPARTMENT_MST> DEPARTMENT_MST { get; set; }
        public virtual DbSet<FG_BOM> FG_BOM { get; set; }
        public virtual DbSet<FG_MST> FG_MST { get; set; }
        public virtual DbSet<GRN_DTL> GRN_DTL { get; set; }
        public virtual DbSet<GRN_LABEL_PRINTING> GRN_LABEL_PRINTING { get; set; }
        public virtual DbSet<GRN_MST> GRN_MST { get; set; }
        public virtual DbSet<GRN_TYPE_MST> GRN_TYPE_MST { get; set; }
        public virtual DbSet<INVENTORY_DTL> INVENTORY_DTL { get; set; }
        public virtual DbSet<INVENTORY_MST> INVENTORY_MST { get; set; }
        public virtual DbSet<LABEL_TYPE_MST> LABEL_TYPE_MST { get; set; }
        public virtual DbSet<LOCATION_MST> LOCATION_MST { get; set; }
        public virtual DbSet<MACHINE_MST> MACHINE_MST { get; set; }
        public virtual DbSet<MACHINE_TYPE_MST> MACHINE_TYPE_MST { get; set; }
        public virtual DbSet<MATERIAL_MST> MATERIAL_MST { get; set; }
        public virtual DbSet<MATERIAL_TYPE_MST> MATERIAL_TYPE_MST { get; set; }
        public virtual DbSet<MIXED_PALLET_STO> MIXED_PALLET_STO { get; set; }
        public virtual DbSet<MRN_MST> MRN_MST { get; set; }
        public virtual DbSet<PICKING_DTL> PICKING_DTL { get; set; }
        public virtual DbSet<PROCESS_MST> PROCESS_MST { get; set; }
        public virtual DbSet<PROCESS_TYPE_MST> PROCESS_TYPE_MST { get; set; }
        public virtual DbSet<QC_DTL> QC_DTL { get; set; }
        public virtual DbSet<QC_LABEL_PRINTING> QC_LABEL_PRINTING { get; set; }
        public virtual DbSet<QC_MST> QC_MST { get; set; }
        public virtual DbSet<QC_REJECTION_NOTE> QC_REJECTION_NOTE { get; set; }
        public virtual DbSet<REASON_MST> REASON_MST { get; set; }
        public virtual DbSet<RECEPIE_MST> RECEPIE_MST { get; set; }
        public virtual DbSet<REJECTION_DTL> REJECTION_DTL { get; set; }
        public virtual DbSet<REJECTION_MST> REJECTION_MST { get; set; }
        public virtual DbSet<SCREEN_LIST> SCREEN_LIST { get; set; }
        public virtual DbSet<SERIAL_CONTROL_MST> SERIAL_CONTROL_MST { get; set; }
        public virtual DbSet<SITE_MST> SITE_MST { get; set; }
        public virtual DbSet<STATUS_MST> STATUS_MST { get; set; }
        public virtual DbSet<STO_MST> STO_MST { get; set; }
        public virtual DbSet<UOM_MST> UOM_MST { get; set; }
        public virtual DbSet<USER_MST> USER_MST { get; set; }
        public virtual DbSet<USER_ROLE_ACCESS_MST> USER_ROLE_ACCESS_MST { get; set; }
        public virtual DbSet<USER_ROLE_MST> USER_ROLE_MST { get; set; }
        public virtual DbSet<PICKING_MST> PICKING_MST { get; set; }
    
        [DbFunction("AI_BTS_DENSOEntities1", "GET_PART_NO_NAME_BY_BARCODE")]
        public virtual IQueryable<GET_PART_NO_NAME_BY_BARCODE_Result> GET_PART_NO_NAME_BY_BARCODE(string bARCODE)
        {
            var bARCODEParameter = bARCODE != null ?
                new ObjectParameter("BARCODE", bARCODE) :
                new ObjectParameter("BARCODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GET_PART_NO_NAME_BY_BARCODE_Result>("[AI_BTS_DENSOEntities1].[GET_PART_NO_NAME_BY_BARCODE](@BARCODE)", bARCODEParameter);
        }
    
        [DbFunction("AI_BTS_DENSOEntities1", "GET_QC_BARCODE_SERIAL")]
        public virtual IQueryable<GET_QC_BARCODE_SERIAL_Result> GET_QC_BARCODE_SERIAL(string pART_NO, string a_NOTICVE_NO, Nullable<int> qTY, Nullable<int> pACK_SIZE, string pRIMARY_BARCODE, string sITE_NAME, Nullable<int> qC_BY, Nullable<System.DateTime> qC_ON)
        {
            var pART_NOParameter = pART_NO != null ?
                new ObjectParameter("PART_NO", pART_NO) :
                new ObjectParameter("PART_NO", typeof(string));
    
            var a_NOTICVE_NOParameter = a_NOTICVE_NO != null ?
                new ObjectParameter("A_NOTICVE_NO", a_NOTICVE_NO) :
                new ObjectParameter("A_NOTICVE_NO", typeof(string));
    
            var qTYParameter = qTY.HasValue ?
                new ObjectParameter("QTY", qTY) :
                new ObjectParameter("QTY", typeof(int));
    
            var pACK_SIZEParameter = pACK_SIZE.HasValue ?
                new ObjectParameter("PACK_SIZE", pACK_SIZE) :
                new ObjectParameter("PACK_SIZE", typeof(int));
    
            var pRIMARY_BARCODEParameter = pRIMARY_BARCODE != null ?
                new ObjectParameter("PRIMARY_BARCODE", pRIMARY_BARCODE) :
                new ObjectParameter("PRIMARY_BARCODE", typeof(string));
    
            var sITE_NAMEParameter = sITE_NAME != null ?
                new ObjectParameter("SITE_NAME", sITE_NAME) :
                new ObjectParameter("SITE_NAME", typeof(string));
    
            var qC_BYParameter = qC_BY.HasValue ?
                new ObjectParameter("QC_BY", qC_BY) :
                new ObjectParameter("QC_BY", typeof(int));
    
            var qC_ONParameter = qC_ON.HasValue ?
                new ObjectParameter("QC_ON", qC_ON) :
                new ObjectParameter("QC_ON", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GET_QC_BARCODE_SERIAL_Result>("[AI_BTS_DENSOEntities1].[GET_QC_BARCODE_SERIAL](@PART_NO, @A_NOTICVE_NO, @QTY, @PACK_SIZE, @PRIMARY_BARCODE, @SITE_NAME, @QC_BY, @QC_ON)", pART_NOParameter, a_NOTICVE_NOParameter, qTYParameter, pACK_SIZEParameter, pRIMARY_BARCODEParameter, sITE_NAMEParameter, qC_BYParameter, qC_ONParameter);
        }
    
        public virtual ObjectResult<SP_CHECK_IF_GRN_DONE_Result> SP_CHECK_IF_GRN_DONE(string qC_TYPE, string bARCODE)
        {
            var qC_TYPEParameter = qC_TYPE != null ?
                new ObjectParameter("QC_TYPE", qC_TYPE) :
                new ObjectParameter("QC_TYPE", typeof(string));
    
            var bARCODEParameter = bARCODE != null ?
                new ObjectParameter("BARCODE", bARCODE) :
                new ObjectParameter("BARCODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CHECK_IF_GRN_DONE_Result>("SP_CHECK_IF_GRN_DONE", qC_TYPEParameter, bARCODEParameter);
        }
    
        public virtual int SP_GET_BARCODE_SERIAL(string bARCODE_TYPE, ObjectParameter serial)
        {
            var bARCODE_TYPEParameter = bARCODE_TYPE != null ?
                new ObjectParameter("BARCODE_TYPE", bARCODE_TYPE) :
                new ObjectParameter("BARCODE_TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_BARCODE_SERIAL", bARCODE_TYPEParameter, serial);
        }
    
        public virtual ObjectResult<SP_GET_GRN_DATA_FOR_QC_Result> SP_GET_GRN_DATA_FOR_QC(string a_NOTICE_NO)
        {
            var a_NOTICE_NOParameter = a_NOTICE_NO != null ?
                new ObjectParameter("A_NOTICE_NO", a_NOTICE_NO) :
                new ObjectParameter("A_NOTICE_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_GRN_DATA_FOR_QC_Result>("SP_GET_GRN_DATA_FOR_QC", a_NOTICE_NOParameter);
        }
    
        public virtual ObjectResult<SP_GET_PALLET_LIST_Result> SP_GET_PALLET_LIST(string a_NOTICE_NO, string pALLET_NO)
        {
            var a_NOTICE_NOParameter = a_NOTICE_NO != null ?
                new ObjectParameter("A_NOTICE_NO", a_NOTICE_NO) :
                new ObjectParameter("A_NOTICE_NO", typeof(string));
    
            var pALLET_NOParameter = pALLET_NO != null ?
                new ObjectParameter("PALLET_NO", pALLET_NO) :
                new ObjectParameter("PALLET_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_PALLET_LIST_Result>("SP_GET_PALLET_LIST", a_NOTICE_NOParameter, pALLET_NOParameter);
        }
    
        public virtual ObjectResult<SP_GET_QC_DATA_BY_ANOTICENO_Result> SP_GET_QC_DATA_BY_ANOTICENO(string a_NOTICE_NO)
        {
            var a_NOTICE_NOParameter = a_NOTICE_NO != null ?
                new ObjectParameter("A_NOTICE_NO", a_NOTICE_NO) :
                new ObjectParameter("A_NOTICE_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_QC_DATA_BY_ANOTICENO_Result>("SP_GET_QC_DATA_BY_ANOTICENO", a_NOTICE_NOParameter);
        }
    
        public virtual int SP_INSERT_QC_MST_DATA(string qC_TYPE, string qC_ACTION, string a_NOTICE_NO, Nullable<int> gRN_DTL_ID, Nullable<int> pACK_SIZE, Nullable<int> qTY_APPROVED, Nullable<int> qTY_REJECTED, Nullable<int> qTY_SCRAPPED, string pRIMARY_BARCODE, Nullable<int> qC_BY, Nullable<System.DateTime> qC_ON)
        {
            var qC_TYPEParameter = qC_TYPE != null ?
                new ObjectParameter("QC_TYPE", qC_TYPE) :
                new ObjectParameter("QC_TYPE", typeof(string));
    
            var qC_ACTIONParameter = qC_ACTION != null ?
                new ObjectParameter("QC_ACTION", qC_ACTION) :
                new ObjectParameter("QC_ACTION", typeof(string));
    
            var a_NOTICE_NOParameter = a_NOTICE_NO != null ?
                new ObjectParameter("A_NOTICE_NO", a_NOTICE_NO) :
                new ObjectParameter("A_NOTICE_NO", typeof(string));
    
            var gRN_DTL_IDParameter = gRN_DTL_ID.HasValue ?
                new ObjectParameter("GRN_DTL_ID", gRN_DTL_ID) :
                new ObjectParameter("GRN_DTL_ID", typeof(int));
    
            var pACK_SIZEParameter = pACK_SIZE.HasValue ?
                new ObjectParameter("PACK_SIZE", pACK_SIZE) :
                new ObjectParameter("PACK_SIZE", typeof(int));
    
            var qTY_APPROVEDParameter = qTY_APPROVED.HasValue ?
                new ObjectParameter("QTY_APPROVED", qTY_APPROVED) :
                new ObjectParameter("QTY_APPROVED", typeof(int));
    
            var qTY_REJECTEDParameter = qTY_REJECTED.HasValue ?
                new ObjectParameter("QTY_REJECTED", qTY_REJECTED) :
                new ObjectParameter("QTY_REJECTED", typeof(int));
    
            var qTY_SCRAPPEDParameter = qTY_SCRAPPED.HasValue ?
                new ObjectParameter("QTY_SCRAPPED", qTY_SCRAPPED) :
                new ObjectParameter("QTY_SCRAPPED", typeof(int));
    
            var pRIMARY_BARCODEParameter = pRIMARY_BARCODE != null ?
                new ObjectParameter("PRIMARY_BARCODE", pRIMARY_BARCODE) :
                new ObjectParameter("PRIMARY_BARCODE", typeof(string));
    
            var qC_BYParameter = qC_BY.HasValue ?
                new ObjectParameter("QC_BY", qC_BY) :
                new ObjectParameter("QC_BY", typeof(int));
    
            var qC_ONParameter = qC_ON.HasValue ?
                new ObjectParameter("QC_ON", qC_ON) :
                new ObjectParameter("QC_ON", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERT_QC_MST_DATA", qC_TYPEParameter, qC_ACTIONParameter, a_NOTICE_NOParameter, gRN_DTL_IDParameter, pACK_SIZEParameter, qTY_APPROVEDParameter, qTY_REJECTEDParameter, qTY_SCRAPPEDParameter, pRIMARY_BARCODEParameter, qC_BYParameter, qC_ONParameter);
        }
    
        public virtual int SP_UPDATE_GRN_LBL_PRINTING_QC_STATUS(string qC_TYPE, string bARCODE, Nullable<int> sTATUS)
        {
            var qC_TYPEParameter = qC_TYPE != null ?
                new ObjectParameter("QC_TYPE", qC_TYPE) :
                new ObjectParameter("QC_TYPE", typeof(string));
    
            var bARCODEParameter = bARCODE != null ?
                new ObjectParameter("BARCODE", bARCODE) :
                new ObjectParameter("BARCODE", typeof(string));
    
            var sTATUSParameter = sTATUS.HasValue ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_GRN_LBL_PRINTING_QC_STATUS", qC_TYPEParameter, bARCODEParameter, sTATUSParameter);
        }
    
        public virtual int SP_UPDATE_QC_MST_DTL_STATUS(string qC_TYPE, string a_NOTICE_NO, string pART_NO, string bARCODE, Nullable<int> qC_BY, Nullable<int> sTATUS)
        {
            var qC_TYPEParameter = qC_TYPE != null ?
                new ObjectParameter("QC_TYPE", qC_TYPE) :
                new ObjectParameter("QC_TYPE", typeof(string));
    
            var a_NOTICE_NOParameter = a_NOTICE_NO != null ?
                new ObjectParameter("A_NOTICE_NO", a_NOTICE_NO) :
                new ObjectParameter("A_NOTICE_NO", typeof(string));
    
            var pART_NOParameter = pART_NO != null ?
                new ObjectParameter("PART_NO", pART_NO) :
                new ObjectParameter("PART_NO", typeof(string));
    
            var bARCODEParameter = bARCODE != null ?
                new ObjectParameter("BARCODE", bARCODE) :
                new ObjectParameter("BARCODE", typeof(string));
    
            var qC_BYParameter = qC_BY.HasValue ?
                new ObjectParameter("QC_BY", qC_BY) :
                new ObjectParameter("QC_BY", typeof(int));
    
            var sTATUSParameter = sTATUS.HasValue ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_QC_MST_DTL_STATUS", qC_TYPEParameter, a_NOTICE_NOParameter, pART_NOParameter, bARCODEParameter, qC_BYParameter, sTATUSParameter);
        }
    }
}
