//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPARTMENT_MST()
        {
            this.MACHINE_MST = new HashSet<MACHINE_MST>();
        }
    
        public int DEPARTMENT_MST_ID { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public Nullable<int> ACTIVE { get; set; }
    
        public virtual ACTIVE_MST ACTIVE_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MACHINE_MST> MACHINE_MST { get; set; }
    }
}
