//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FG_BOM
    {
        public int FG_BOM_MST_ID { get; set; }
        public Nullable<int> FG_MST_ID { get; set; }
        public Nullable<int> FG_QTY { get; set; }
        public Nullable<int> INPUT_MATERIAL_ID { get; set; }
        public Nullable<int> INPUT_MATERIAL_QTY { get; set; }
        public Nullable<int> INPUT_MATERIAL_UOM_ID { get; set; }
    
        public virtual MATERIAL_MST MATERIAL_MST { get; set; }
        public virtual UOM_MST UOM_MST { get; set; }
    }
}
