//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRN_LABEL_PRINTING
    {
        public int LBL_PRN_CFM { get; set; }
        public Nullable<int> GRN_DTL_ID { get; set; }
        public string PRIMARY_BARCODE { get; set; }
        public int BR_SERIAL { get; set; }
        public Nullable<int> LABEL_TYPE_MST_ID { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string TODAY_BARCODE_SERIAL { get; set; }
        public Nullable<int> BOX_QUANTITY { get; set; }
        public string PALLETE_NO_BARCODE { get; set; }
        public string PRINT_TYPE { get; set; }
    
        public virtual GRN_DTL GRN_DTL { get; set; }
        public virtual USER_MST USER_MST { get; set; }
        public virtual LABEL_TYPE_MST LABEL_TYPE_MST { get; set; }
    }
}
