//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_DTL
    {
        public int INVD_REC_ID { get; set; }
        public Nullable<int> INV_MST_ID { get; set; }
        public string P_BARCODE { get; set; }
        public string C_BARCODE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> QUANTITY_ISSUED { get; set; }
        public Nullable<int> QUANTITY_REMAINING { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        public virtual INVENTORY_MST INVENTORY_MST { get; set; }
    }
}
