//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVENTORY_MST()
        {
            this.INVENTORY_DTL = new HashSet<INVENTORY_DTL>();
        }
    
        public int INV_MST_ID { get; set; }
        public Nullable<int> QC_MST_ID { get; set; }
        public string PART_NO { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> QUANTITY_ISSUED { get; set; }
        public Nullable<int> QUANTITY_REMAINING { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> SITE_MST_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY_DTL> INVENTORY_DTL { get; set; }
        public virtual QC_MST QC_MST { get; set; }
        public virtual SITE_MST SITE_MST { get; set; }
    }
}
