//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MACHINE_MST
    {
        public int MACHINE_MST_ID { get; set; }
        public string MACHINE_NAME { get; set; }
        public Nullable<int> MACHINE_TYPE_MST_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> PROCESS_MST_ID { get; set; }
        public Nullable<int> DEPARTMENT_MST_ID { get; set; }
        public Nullable<int> ACTIVE { get; set; }
    
        public virtual DEPARTMENT_MST DEPARTMENT_MST { get; set; }
        public virtual MACHINE_TYPE_MST MACHINE_TYPE_MST { get; set; }
        public virtual PROCESS_MST PROCESS_MST { get; set; }
    }
}
