//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIXED_PALLET_STO
    {
        public int STO_MST_ID { get; set; }
        public string STO_NO { get; set; }
        public string MIXED_PALLET_NO { get; set; }
        public Nullable<System.DateTime> STO_TIME { get; set; }
        public Nullable<System.DateTime> GRN_PRINTING_TIME { get; set; }
        public Nullable<int> GRN_DTL_ID { get; set; }
        public Nullable<int> IS_PICKED { get; set; }
        public Nullable<int> IS_DISPATCHED { get; set; }
    }
}
