//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRN_MST
    {
        public int MRN_MST_ID { get; set; }
        public string MRN_NO { get; set; }
        public string PART_NO { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> SITE_MST_ID { get; set; }
        public Nullable<int> DISPATCH_BY { get; set; }
        public Nullable<System.DateTime> DISPATCH_ON { get; set; }
        public string KANBAN_TEXT { get; set; }
    }
}
