//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESS_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROCESS_MST()
        {
            this.MACHINE_MST = new HashSet<MACHINE_MST>();
        }
    
        public int PROCESS_MST_ID { get; set; }
        public string PROCESS_NAME { get; set; }
        public Nullable<int> PROCESS_TYPE_MST_ID { get; set; }
        public string SEQUENCE { get; set; }
        public Nullable<int> FG_MST_ID { get; set; }
        public Nullable<int> ACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MACHINE_MST> MACHINE_MST { get; set; }
        public virtual PROCESS_TYPE_MST PROCESS_TYPE_MST { get; set; }
    }
}
