//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_DTL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QC_DTL()
        {
            this.QC_LABEL_PRINTING = new HashSet<QC_LABEL_PRINTING>();
        }
    
        public int QC_DTL_ID { get; set; }
        public Nullable<int> QC_MST_ID { get; set; }
        public string PRIMARY_BARCODE { get; set; }
        public Nullable<int> QUANTITY_APPROVED { get; set; }
        public Nullable<int> QUANTITY_REJECTED { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> QUANTITY_SCRAPPED { get; set; }
        public Nullable<int> QUANTITY_PICKED { get; set; }
        public Nullable<int> QUANTITY_RETURN { get; set; }
    
        public virtual QC_MST QC_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QC_LABEL_PRINTING> QC_LABEL_PRINTING { get; set; }
    }
}
