//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_LABEL_PRINTING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QC_LABEL_PRINTING()
        {
            this.COIL_QC_DETAILS = new HashSet<COIL_QC_DETAILS>();
        }
    
        public int QC_LBL_ID { get; set; }
        public Nullable<int> QC_DTL_ID { get; set; }
        public string PARENT_BARCODE { get; set; }
        public string QC_BARCODE { get; set; }
        public Nullable<int> BARCODE_TYPE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> PACK_SIZE { get; set; }
        public string TODAY_BARCODE_SERIAL { get; set; }
        public Nullable<System.DateTime> QC_ON { get; set; }
        public Nullable<int> QC_BY { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COIL_QC_DETAILS> COIL_QC_DETAILS { get; set; }
        public virtual QC_DTL QC_DTL { get; set; }
    }
}
