//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QC_MST()
        {
            this.INVENTORY_MST = new HashSet<INVENTORY_MST>();
            this.QC_DTL = new HashSet<QC_DTL>();
        }
    
        public int QC_MST_ID { get; set; }
        public Nullable<int> GRN_DTL_ID { get; set; }
        public string PART_NO { get; set; }
        public string A_NOTICE_NO { get; set; }
        public Nullable<int> QUANTITY_TOTAL { get; set; }
        public Nullable<int> QUANTITY_APPROVED { get; set; }
        public Nullable<int> QUANTITY_REJECTED { get; set; }
        public Nullable<int> QUANTITY_SCRAPPED { get; set; }
        public string SUPPLIER_BATCH_NO { get; set; }
        public Nullable<int> QC_BY { get; set; }
        public Nullable<System.DateTime> QC_ON { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        public virtual GRN_DTL GRN_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY_MST> INVENTORY_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QC_DTL> QC_DTL { get; set; }
        public virtual USER_MST USER_MST { get; set; }
    }
}
