//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_REJECTION_NOTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QC_REJECTION_NOTE()
        {
            this.REJECTION_DTL = new HashSet<REJECTION_DTL>();
        }
    
        public int QC_NOTE_ID { get; set; }
        public Nullable<int> PART_NO { get; set; }
        public string PART_NAME { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
    
        public virtual USER_MST USER_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REJECTION_DTL> REJECTION_DTL { get; set; }
    }
}
