//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REASON_MST
    {
        public int REASON_MST_ID { get; set; }
        public string REASON_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ACTIVE { get; set; }
    }
}
