//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEPIE_MST
    {
        public int RECEPIE_ID { get; set; }
        public string RECEPIE_NAME { get; set; }
        public Nullable<int> PROCESS_MST_ID { get; set; }
        public Nullable<int> OUTPUT_FG_MST_ID { get; set; }
        public Nullable<int> OUTPUT_FG_QTY { get; set; }
        public Nullable<int> ACTIVE { get; set; }
    
        public virtual FG_MST FG_MST { get; set; }
    }
}
