//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REJECTION_DTL
    {
        public int WC_RJN_ID { get; set; }
        public Nullable<int> QC_NOTE_ID { get; set; }
        public string QC_BARCODE { get; set; }
    
        public virtual QC_REJECTION_NOTE QC_REJECTION_NOTE { get; set; }
    }
}
