//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERIAL_CONTROL_MST
    {
        public long SERIAL_MST_ID { get; set; }
        public Nullable<System.DateTime> SERIAL_DATE { get; set; }
        public Nullable<long> TODAY_BARCODE_SERIAL { get; set; }
        public string TARGET_MST { get; set; }
    }
}
