//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STO_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STO_MST()
        {
            this.PICKING_MST = new HashSet<PICKING_MST>();
        }
    
        public int MRN_MST_ID { get; set; }
        public string MRN_NO { get; set; }
        public string REFERENCE_NO { get; set; }
        public string PART_NO { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> SITE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PICKING_MST> PICKING_MST { get; set; }
        public virtual USER_MST USER_MST { get; set; }
    }
}
