//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempColiQC
    {
        public int ID { get; set; }
        public string BARCODE { get; set; }
        public string LOT_NO { get; set; }
        public Nullable<int> PALET_NO { get; set; }
        public Nullable<int> SERIAL_NO { get; set; }
        public Nullable<int> WEIGHT { get; set; }
    }
}
