//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_BTS_DENSO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ROLE_ACCESS_MST
    {
        public int USER_ROLE_ACCESS_MST_ID { get; set; }
        public Nullable<int> USER_ROLE_MST_ID { get; set; }
        public string SCREEN_NAME { get; set; }
        public Nullable<int> READ_ACCESS { get; set; }
        public Nullable<int> ADD_ACCESS { get; set; }
        public Nullable<int> DELETE_ACCESS { get; set; }
    
        public virtual USER_ROLE_MST USER_ROLE_MST { get; set; }
    }
}
